
[selene]
base = "lua51"
name = "extension"

[getgenv]
args = []
[getreg]
args = []
[checkcaller]
args = []
[HANDLE_TELEPORT]
args = []

[[setclipboard.args]]
required = true
type = "string"

[getloadedmodules]
args = []
[getinstancecachekey]
args = []
[getinstances]
args = []
[getnilinstances]
args = []

[gethui]
args = []

[[getrawmetatable.args]]
required = true
type = { display = "Instance" }

[getnamecallmethod]
args = []
[[setnamecallmethod.args]]
required = true
type = "string"

[[lockModule.args]]
required = true
type = { display = "ModuleScript" }
[[unlockModule.args]]
required = true
type = { display = "ModuleScript" }

[[setreadonly.args]]
required = true
type = "table"
[[setreadonly.args]]
required = true
type = "bool"

[[newcclosure.args]]
required = true
type = "function"
[[iscclosure.args]]
required = true
type = "function"
[[islclosure.args]]
required = true
type = "function"

[[hookfunction.args]]
required = true
type = "function"
[[hookfunction.args]]
required = true
type = "function"

[[readfile.args]]
required = true
type = "string"
[[listfiles.args]]
required = true
type = "string"
[[isfolder.args]]
required = true
type = "string"
[[isfile.args]]
required = true
type = "string"
[[writefile.args]]
required = true
type = "string"
[[writefile.args]]
required = true
type = "string"
[[makefolder.args]]
required = true
type = "string"
[[delfolder.args]]
required = true
type = "string"

[[request.args]]
required = true
type = "string"
[getnetworkmode]
args = []
[[setnetworkmode.args]]
type = "number"

[[getconnections.args]]
required = true
type = { display = "RBXScriptSignal" }

["..."]
property = true
[ROOT]
property = true

[isluau]
property = true
[iskrnlclosure]
property = true